name: Automation Exercise CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install System Dependencies for Ubuntu 24.04
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 libvpx9 libevent-2.1-7 libopus0 libsecret-1-0 libhyphen0 libx264-dev

      - name: Install Playwright Browsers
        env:
          PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: true
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium"

      - name: Run Tests
        run: mvn clean test -Dheadless=true

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Send email on completion
        if: success() || failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          subject: "GitHub Actions Status: ${{ job.status }}"
          body: |
            التيست خلص وحالته: ${{ job.status }}
            التقرير موجود أونلاين هنا: https://mekkihassan.github.io/automationexercise/
          to: mekkihassan02@gmail.com
          from: GitHub Actions

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # ده المسار الافتراضي اللي الـ Plugin بيحط فيه التقرير بعد الـ mvn allure:report
            publish_dir: ./target/site/allure-maven-plugin
            force_orphan: true
            user_name: 'github-actions[bot]'
            user_email: 'github-actions[bot]@users.noreply.github.com'